[master]
k8s-master ansible_host=35.189.63.185

[workers]
k8s-worker-1 ansible_host=34.151.160.227
k8s-worker-2 ansible_host=34.151.146.75

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_ssh_common_args='-o StrictHostKeyChecking=no'